### ISSUE TITLE
Picture in Wiki

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1568]
Hello,
It is not possible for me to add an image in the wiki whether it is in .jpg or in .png. Despite the fact that I click on "import to server", the image does not upload.
<img width="933" alt="image impossible 111" src="https://user-images.githubusercontent.com/40500094/114891692-17a43180-9dda-11eb-93a6-04b9fb8cdb48.png">
<img width="939" alt="image impossible" src="https://user-images.githubusercontent.com/40500094/114891703-1a068b80-9dda-11eb-946e-3e3a1cd016ad.png">

--

Bonjour,
Il m'est impossible d'ajouter une image dans le wiki qu'elle soit en .jpg ou en .png. Malgré le fait que je clique sur "importer sur le serveur", l'image ne se téléverse pas.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks,
Ayesha

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-3048

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Could you please just rename the jpg image that you are trying to upload & then give it another try, as the same scenario worked for me? Let me know if it works for you?
Thanks,
Ayesha Aamer

**Comment by JessicaSOS** [comment]
I try to rename the file and import it again ... but without success.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Hope you are doing well. Definitely strange! Could you please share any of the two images that you are trying to upload, so that I can further investigate the reported issue with our development team? 
Thanks,
Ayesha Aamer

**Comment by JessicaSOS** [comment]
Here is the picture
![ipad 129](https://user-images.githubusercontent.com/40500094/115421975-772f8200-a1ca-11eb-8828-bc3d4a85dd3e.jpg)

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Thanks for the image. I have tried with the above image as well and it worked for me. I have just changed the name of the image provided by you and it successfully gets uploaded in the Wiki. Kindly see the video attached below, hope it helps. Please let me know if I am able to answer your question.
Thanks,
Ayesha Aamer
https://drive.google.com/file/d/1NHjk9xbZBqEiuLso7w_gU1QuIVVpLgiu/view

**Comment by JessicaSOS** [comment]
The same steps are precisely done on my side, but I am still unable to import the image. I tried with google chrome and microsoft edge.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Ayesha here. I hope you are doing well. Definitely strange! I tried again and it worked for me. Can you please connect with one of our support agent on live chat so that he can look into the issue you are facing in detail? Thanks!

**Comment by JessicaSOS** [comment]
I don't see how anyone on the chat is going to be able to help me with this. Here is the video on my profile.

https://www.awesomescreenshot.com/video/3480230?key=5f326ffa2d8d61d87e53097187098d11

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA Can you check this again?

**Comment by JessicaSOS** [comment]
any news ?

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Ayesha here. I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try? 
Thanks!

**Comment by JessicaSOS** [comment]
Still does not work

**Comment by fahadimran303** [comment]
**Hello Jessica,**

Fahad here, Manager Client Success & Support.

I have been trying to reach out on your number however I am unable to connect with you.

Is there a possibility you may book a timeslot from the link below:
https://calendly.com/fahadimran

I am going to call you on Tuesday, 25th May in order to further discuss the issue you are facing. It would be great if you can book a slot from the link I shared above.

**Thanks and Regards,**

**Comment by JessicaSOS** [comment]
Hello Fahad,
I know how to import an image. I demonstrated to you by video the steps that I carried out. I don't think I'm wrong, but if so, I would like you to let me know. I am very busy and would like you to look into the problem without me as much as possible. What are your questions?
I don't think I have to be "live" with you to sort this out. You can schedule a time slot in your calendar to look at this. You have the picture a little higher. What is the problem ??
thanks for getting back to me

**Comment by JessicaSOS** [comment]
Same thing here. The problem is still here.
I work to report problems to you and close tasks to you without even asking you about the problem. This is not resolved so please reopen

**Comment by JessicaSOS** [comment]
We're talking about a photo and I'm still waiting ...
reopen

**Comment by JessicaSOS** [comment]
When are we going to be able to put the simple photo in our wiki article?

**Comment by Repairdesk-QA** [comment]
Hi @JessicaSOS,
Ayesha here. I hope you are doing well. I have checked your concern but everything is working fine on my end. 
I will request you to schedule a call with **Fahad Imran, Manager Customer Success and Support**. Kindly book a slot from the link in order to connect with him:
https://calendly.com/fahadimran
I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.
Thank you!

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

I hope you have scheduled a call with **_Fahad Imran_** & your issue has been resolved.
Kindly let us know if you still have the issue.
Waiting for your kind response!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain

**Comment by JessicaSOS** [comment]
I will not schedule a call to correct this. You have all the information on your side to be able to solve this problem. You can try to put the image yourself in the wiki text and you will see.

If the ticket is still open, it is not settled. Problems do not resolve themselves. If you didn't do anything, the problem is still there.

I still have this problem on my side, Please reopen the ticket. See this link for video of the problem

https://www.awesomescreenshot.com/video/6422776?key=0f7db1c147bbad8422f2c2d2afc02a46

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Sorry for the continued inconvenience. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Your patience would be highly appreciated.
Thanks!
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
**For internal use:**
https://repairdesk.atlassian.net/browse/RB-3048

**Comment by Repairdesk-QA** [comment]
**Hey @JessicaSOS,**
**I hope you are doing well.**

I have checked your concern with our development team on your RepairDesk account as well and the issue is not reproduced. Kindly have a look at the attached video. Plus the issue is not reproduced even on my test account as well. Could you please give it another try? Will be waiting for your reply.
https://watch.screencastify.com/v/CKZevRiNUDS1yISAES7Y 

**Thanks,**
**_Ayesha Aamir_**

**Comment by Repairdesk-QA** [comment]
_**Hey @JessicaSOS,**_
**Hope you are doing well.** 

As you mentioned above I have uploaded the above mentioned image to your Repairdesk account in the **Wiki > Chatr > Nip de boite vocal (code à 4 chiffres) > Requested image upload**. Hope it helps.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Closing this task for now. 
Have a good day! 

_**Regards,**_
_**Ayesha Aamir**_

**Comment by JessicaSOS** [comment]
UPDATE

I cannot change it category. Can you go put the image please in: "reparation", "Apple", the last one "reparation iPad 12.9" and save the image under the current text please.

Thank you very much.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Sure, will update you shortly on this.

**Regards,** 
Ayesha

**Comment by Repairdesk-QA** [comment]
**Hey @JessicaSOS,**

It's done. I have put the image in: "reparation", "Apple" > "reparation iPad 12.9" under the current text. 
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Have a good day. 

**Regards,**
**_Ayesha Aamir_**

**Comment by JessicaSOS** [comment]
fixed, tnx a lot

**Comment by Repairdesk-QA** [comment]
Thanks, @JessicaSOS for your feedback.
I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**_Regards,_**
Quratul Ain
