### ISSUE TITLE
Problem with category in commission section

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#412]
Already postponed on January 28, 2018

I found that the service category appears as an accessory. Yet, I have checked and these products are properly created in service.
See example service item # 9042 "Desjardins worker 10%". There is even an item that does not have an item number.
See Attachment
<img width="937" alt="accessories staff report" src="https://user-images.githubusercontent.com/40500094/44234071-a2d55100-a173-11e8-8d3b-237e5ef02c3f.png">

_--
French:
Déjà reporté le 28 janvier 2018

j'ai trouvé que la catégorie service apparaît en temps qu'accessoire. Pourtant, j'ai vérifié et ces produits est correctement créer en service.
Voir exemple service item #9042 "Travailleur Desjardins 10%". Il y a même un item qui n'a pas de numéro d'item.
Voir pièce jointe_

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We’ve gone live with following improvements in employee commission module: 
1: Employee commission can be set in amount or percentage
2: Commission value can be set globally, with respect to inventory item categories e.g. cases, chargers or individual items too.
3: Setup to split commission between a sales person and technician
4: Configuration to set commission based on total sales or profit earned (Trigger based). A lot of repair stores requested this 
5: Added an option to void commission in case of a refund (Trigger based)
6: Option to pay commission via payroll module.
7: Improved Commission report

I hope this issue is fixed in this release. Please check on your end and if you have any question do let me know. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS  - I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Usman Ali

**Comment by JessicaSOS** [comment]
ok i will test

**Comment by JessicaSOS** [comment]
The service category is still in the accessories category. Not all products in the service category are displayed, but this is not fixed.

**Comment by JessicaSOS** [comment]
I have not received any development regarding the commission module that still does not work properly. In the "sales report by item" the item total is 220 for: Employee: Stephanie + Store: SOS Phone Limoilou + Date: Nov. 1 - Nov. 30, 2018 + Category "product". The result includes trade in. When I make a trade in report with the same search filters, I have a total of 43. However, it is not the same trade in that are in the "product" versus "trade in" category.
Also, in the "My Commission Report" report, the total for the same search filter is 185. The difference is huge. What is the good result? What do I have to pay to the employee?
In 1 month, it's going to be over a year since I wait for commissions to be corrected. I must rely on your reports for the payment of my employees, but your reports are never corrected. Can you make the patches very quickly please, because I have to break my head every month for the commissions of my employees for 5 stores ... It's a big waste of time !!

<img width="941" alt="sale report by item" src="https://user-images.githubusercontent.com/40500094/49387978-0e2a3b00-f6f1-11e8-9948-71285556f3dc.png">

<img width="942" alt="sale report result" src="https://user-images.githubusercontent.com/40500094/49388058-39148f00-f6f1-11e8-8a87-ea382379ff9c.png">

<img width="942" alt="my commission report" src="https://user-images.githubusercontent.com/40500094/49388121-5a757b00-f6f1-11e8-9253-1fa69205591f.png">

--
french:
Je n'ai recu aucun dveloppement concernant le module de commission qui ne fonctionne toujours pas correctement. Dans le "rapport des ventes par item" le total d'item est 220 pour: Employé: Stéphanie + Magasin: SOS Phone Limoilou + Date: 1 nov. au 30 nov. 2018 + Catégorie "product". Le résultat inclus des trade in. Quand je fais un rapport de trade in avec les mêmes filtres de recherche, j'ai un total de 43. Cependant, ce n'est pas les mêmes trade in qui sont dans la catégorie "product" versus "trade in". 
Aussi, dans le rapoprt "My Commission Report", le total pour les même filtre de recherche est le 185. La différence est énorme. Quel est le bon résultat? Qu'est ce que je dois payer à l'employé? 
Dans 1 mois, ça va faire plus d'un an que j'attends que les commissions soit corrigé. Je doit me fier à vos rapports pour le paiement de mes employés, mais vos rapport ne sont jamais corrigé. Pouvez-vous faire les correctifs très rapidement svp, car je dois me casser la tête à chaque mois pour les commissions de mes employés pour 5 magasins... C'est de la grosse perte de temps !!
