### ISSUE TITLE
Macros problem (Tag)

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#706]
Hello,
All tags "Macros" do not work in the notifications and email programs. Thank you for correcting quickly, because it's been a long time since the problem is present and every day, dozens of customers receive
Hello Customer name,
{store_name}  
{store_address}  
{store_email}  
{store_website}  
{store_phone} 
  It's not very professional.

See example:
Issues already reported (October 2018) that correspond to this problem:
Tag in From the reminder reminder # 463
Tag in customer portal # 462
Tag in Payment confirmation email # 464
From the reminder invoice # 417
<img width="672" alt="appointement confirmation up" src="https://user-images.githubusercontent.com/40500094/53974886-9d206800-40d1-11e9-8c2d-82c237a1bafe.png">

___
French:
Bonjour,
Tous les tag "Macros" ne fonctionne pas dans les programations des notifications et courriels. Merci de corrigé rapidement, car cela fait longtemps que le problème est présent et tous les jours, des dizaines de clients recoivent 
Bonjour Customer name,
{store_name}  
{store_address}  
{store_email}  
{store_website}  
{store_phone} 
 Sa ne fait pas très professionnel.

Voir exemple: 
Issues déjà reporté (octobre 2018) qui correspondent à ce problème:
Tag in Du invoice reminder #463
Tag in customer portal #462
Tag in Payment confirmation email #464
Du invoice reminder #417

**Comment by JessicaSOS** [comment]
I receive emails every day from customers telling us that his name is not David Fournier because this name appears in all appointments confirmations. There is also plenty of unfilled placeholder or not working properly.
Thank you so quickly correct.
Have a good day

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure let me check this on my end and will revert back to you with more information.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue related to {device} and {date_time} has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
To test # 706 & # 462
For text messages it is corrected, but not for emails. I do not receive them all during an appointment confirmation or when sending the portal link to the client. And, in Lévis store, despite the fact that the message is the same as limoilou in the configuration, I received the message of a ticket "waiting for parts", instead of a confirmation of an appointment a lead. I do not understand.

--
French :
Pour tester # 706 & # 462
Pour les texto c'est corrigé, mais pas pour les courriels. Je ne les reçoit pas tout lors d'une confirmation de rendez-vous ou lors de l'envois du lien du portail au client. Deplus, à Lévis, malgré le fait que le message est le même qu'à limoilou dans la configuration, j'ai reçu le message d'un billet "waiting for parts", au lieu d'une confirmation d'un rendez-vous d'un lead. Je ne comprends pas.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Just for an update, we are making an improvement in Macros. Once it will be done, I will update you here. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
not fixed yet !

**Comment by JessicaSOS** [comment]
Hello,
Several TAGs still do not work. It really does not work when we send messages to customers. When will it be corrected? It was planned for March but it was not done. I followed you in May, but I never got a return. When will it be done? This is a problem and I think I have been patient ...
--
_French:
bonjour,
Plusieurs TAG ne fonctionennt toujours pas. Ça ne fait vraiment pas professionel lorsque nous envoyons des messages aux clients. Quand se sera corrigé? C'était prévu pour mars mais ça n'a pas été fait. Je vous ai fait un suivi en mai, mais je n'ai jamais eu de retour. Quand se sera fait svp? Il s'agit d'un problème et je crois avoir été patiente..._

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 

We already updated macro's that you highlighted. We also updated macro's in other email templates as well. However, if it's not working for you then please highlight the email template and macro's that are not working and I will get it fixed for you. 

Thank you for your patience. Appreciate it.

**Comment by JessicaSOS** [comment]
I have seen lately that it was not fixed, but you mention me that it is suposed to be reglued in all the issue # enumerated previously?

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Muhammad Uzair Shah <notifications@github.com> 
Envoyé : 17 juillet 2019 01:33
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Macros problem (Tag) (#706)

 

Hey @JessicaSOS <https://github.com/JessicaSOS> 

We already updated macro's that you highlighted. We also updated macro's in other email templates as well. However, if it's not working for you then please highlight the email template and macro's that are not working and I will get it fixed for you.

Thank you for your patience. Appreciate it.

**Comment by JessicaSOS** [comment]
I have seen lately that it was not fixed, but you mention me that it is suposed to be reglued in all the issue # enumerated previously?

**Comment by JessicaSOS** [comment]
Same here ....

**Comment by JessicaSOS** [comment]
You can close this task, but be aware that the problem with # 417 and # 463 has still not been fixed. It would be nice if you could close completed tasks only! 
*** reopen please
